version: '3'

services:
  gorm:
    image: mysql:latest
    restart: always
    command:
      - mysqld
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_ROOT_PASSWORD=gorm
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    container_name: gorm
